TaskManagerV2/TaskManagerV2/Controllers/CommentsManagementController.cs
using Common.Entities;
using DatabaseAccess.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskManagerV2.Annotations;
using TaskManagerV2.ViewModels.BaseViewModels;
using TaskManagerV2.ViewModels.Comments;

namespace TaskManagerV2.Controllers
{
    public class CommentsManagementController : Controller
    {
        private CommentsRepository commentsRepo;
        public CommentsManagementController()
        {
            commentsRepo = new CommentsRepository();
        }

        public void PopulateItem(SaveCommentVM model, Comment item)
        {
            model.AssignedUserId = item.AssignedUserId;
            model.CommentContent = item.CommentContent;
            model.ParentTaskId = item.ParentTaskId;
        }

        public void PopulateViewModel(Comment item, SaveCommentVM model)
        {
            item.AssignedUserId = model.AssignedUserId;
            item.CommentContent = model.CommentContent;
            item.ParentTaskId = model.ParentTaskId;
        }

        [HttpGet]
        public ActionResult Edit(int? id, int parentTaskId)
        {
            UsersRepository usersRepo = new UsersRepository();
            SaveCommentVM model = new SaveCommentVM();
            Comment item = null;
            if (id == null)
                item = new Comment();
            else
                item = commentsRepo.GetById(id.Value);
            PopulateItem(model, item);
            model.Users = usersRepo.GetAll();
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(SaveCommentVM model)
        {
            UsersRepository usersRepo = new UsersRepository();
            Comment item = null;
            if (model.Id <= 0)
                item = new Comment();
            else
                item = commentsRepo.GetById(model.Id);

            PopulateViewModel(item, model);
            model.Users = usersRepo.GetAll();
            if (!ModelState.IsValid)
                return View(model);

            commentsRepo.Save(item);
            return RedirectToAction("Details", "TasksManagement", new { id = model.ParentTaskId });
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            SaveCommentVM model = new SaveCommentVM();
            Comment item = commentsRepo.GetById(id);
            if (model == null)
                return RedirectToAction("Details", "TasksManagement", new { id = model.ParentTaskId });
            PopulateItem(model, item);
            return View(model);
        }
        [HttpPost]
        public ActionResult Delete(SaveCommentVM model)
        {
            Comment item = commentsRepo.GetById(model.Id);
            commentsRepo.Delete(item);
            return RedirectToAction("Details", "TasksManagement", new { id = model.ParentTaskId });
        }
    }
}

TaskManagerV2/TaskManagerV2/Controllers/LogworksManagementController.cs
using Common.Entities;
using DatabaseAccess.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskManagerV2.ViewModels.BaseViewModels;
using TaskManagerV2.ViewModels.Logworks;

namespace TaskManagerV2.Controllers
{
    public class LogworksManagementController : Controller
    {
        private LogworksRepository logworkRepo;
        public LogworksManagementController()
        {
            logworkRepo = new LogworksRepository();
        }

        public void PopulateItem(SaveLogworkVM model, Logwork item)
        {
            model.LoggedHours = item.LoggedHours;
            model.ParentTaskId = item.ParentTaskId;
        }

        public void PopulateViewModel(Logwork item, SaveLogworkVM model)
        {
            item.LoggedHours = model.LoggedHours;
            item.ParentTaskId = model.ParentTaskId;
        }

        [HttpGet]
        public ActionResult Edit(int? id, int parentTaskId)
        {
            SaveLogworkVM model = new SaveLogworkVM();
            Logwork item = null;
            if (id == null)
                item = new Logwork();
            else
                item = logworkRepo.GetById(id.Value);
            PopulateItem(model, item);
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(SaveLogworkVM model)
        {
            Logwork item = null;
            if (model.Id <= 0)
                item = new Logwork();
            else
                item = logworkRepo.GetById(model.Id);

            PopulateViewModel(item, model);
            if (!ModelState.IsValid)
                return View(model);

            logworkRepo.Save(item);
            return RedirectToAction("Details", "TasksManagement", new { id = model.ParentTaskId });
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            SaveLogworkVM model = new SaveLogworkVM();
            Logwork item = logworkRepo.GetById(id);
            if (model == null)
                return RedirectToAction("Details", "TasksManagement", new { id = model.ParentTaskId });
            PopulateItem(model, item);
            return View(model);
        }
        [HttpPost]
        public ActionResult Delete(SaveLogworkVM model)
        {
            Logwork item = logworkRepo.GetById(model.Id);
            logworkRepo.Delete(item);
            return RedirectToAction("Details", "TasksManagement", new { id = model.ParentTaskId });
        }

    }
}

TaskManagerV2/TaskManagerV2/Controllers/TasksManagementController.cs
using Common.Entities;
using DatabaseAccess.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskManagerV2.Models;
using TaskManagerV2.ViewModels.Comments;
using TaskManagerV2.ViewModels.Logworks;
using TaskManagerV2.ViewModels.Shared;
using TaskManagerV2.ViewModels.Tasks;

namespace TaskManagerV2.Controllers
{
    public class TasksManagementController : BaseController<Task, TasksRepository, SaveTaskVM, IndexTaskVM, TasksFilterVM>
    {
        public override void AddItemToIndexVM(IndexTaskVM model)
        {
            UsersRepository usersRepo = new UsersRepository();
            model.Users = usersRepo.GetAll();
        }
        public override void AddItemToSaveVM(SaveTaskVM model)
        {
            UsersRepository usersRepo = new UsersRepository();
            model.Users = usersRepo.GetAll();
        }
        public override void PopulateItem(SaveTaskVM model, Task item)
        {
            model.ParentUserId = AuthenticationManager.LoggedUser.Id;
            model.Title = item.Title;
            model.TaskContent = item.TaskContent;
            model.LoggedHours = item.LoggedHours;
            model.AssignedUserId = item.AssignedUserId;
            model.DateCreation = item.DateCreation;
            model.DateLastEdit = item.DateLastEdit;
        }

        public override void PopulateViewModel(Task item, SaveTaskVM model)
        {
            item.ParentUserId = AuthenticationManager.LoggedUser.Id;
            item.Title = model.Title;
            item.TaskContent = model.TaskContent;
            item.LoggedHours = model.LoggedHours;
            item.AssignedUserId = model.AssignedUserId;
            item.DateCreation = model.DateCreation;
            item.DateLastEdit = model.DateLastEdit;
        }
        [HttpGet]
        public ActionResult Details(TaskDetailsVM model)
        {
            
            TasksRepository tasksRepository = new TasksRepository();
            model.Item = tasksRepository.GetById(model.Id);
            if (model == null)
                return RedirectToAction("Index", "Tasks");

            UsersRepository usersRepository = new UsersRepository();
            model.Users = usersRepository.GetAll();
            CommentsRepository commentsRepo = new CommentsRepository();
            LogworksRepository logworkRepo = new LogworksRepository();
            model.CommentsPager = model.CommentsPager ?? new PagerVM();
            model.CommentsFilter = model.CommentsFilter ?? new CommentsFilterVM();
            model.CommentsFilter.Id = model.Id;
            var filter = model.CommentsFilter.BuildFilter();
            model.CommentsPager.Prefix = "CommentsPager";
            model.CommentsFilter.Prefix = "CommentsFilter";
            model.CommentsPager.ItemsPerPage = model.CommentsPager.ItemsPerPage == 0 ? 5 : model.CommentsPager.ItemsPerPage;
            model.CommentsPager.PageCount = (int)Math.Ceiling(commentsRepo.Count(filter) / (decimal)model.CommentsPager.ItemsPerPage);
            model.CommentsPager.PageCount = model.CommentsPager.PageCount == 0 ? 1 : model.CommentsPager.PageCount;
            model.Comments = commentsRepo.GetAll(filter, model.CommentsPager.CurrentPage, model.CommentsPager.ItemsPerPage);

            model.LogworksPager = model.LogworksPager ?? new PagerVM();
            model.LogworkFilter = model.LogworkFilter ?? new LogworkFilterVM();
            model.LogworkFilter.Id = model.Id;
            var logworkFilter = model.LogworkFilter.BuildFilter();
            model.LogworksPager.Prefix = "LogworksPager";
            model.LogworkFilter.Prefix = "LogworkFilter";
            model.LogworksPager.ItemsPerPage = model.LogworksPager.ItemsPerPage == 0 ? 5 : model.LogworksPager.ItemsPerPage;
            model.LogworksPager.PageCount = (int)Math.Ceiling(logworkRepo.Count(logworkFilter) / (decimal)model.LogworksPager.ItemsPerPage);
            model.LogworksPager.PageCount = model.LogworksPager.PageCount == 0 ? 1 : model.LogworksPager.PageCount;
            model.Logworks = logworkRepo.GetAll(logworkFilter, model.LogworksPager.CurrentPage, model.LogworksPager.ItemsPerPage);

            return View(model);
        }
    }
}

TaskManagerV2/TaskManagerV2/Views/TasksManagement/Delete.cshtml
@model TaskManagerV2.ViewModels.Tasks.SaveTaskVM

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
    <!-- Bootstrap Core CSS -->
    <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- MetisMenu CSS -->
    <link href="/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="/dist/css/sb-admin-2.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <div class="container">
        @Html.Partial("/Views/Shared/Menu.cshtml")
        <h3 style="margin-left: 25%">Are you sure you want to delete this?</h3>
        <div class="row" style="margin-top: 10%">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        User
                    </div>
                    <div class="panel-body">
                        <p class="lead"><strong>@Html.DisplayNameFor(model => model.Title)</strong></p>
                        <p class="lead">@Html.DisplayFor(model => model.Title)</p>
                        <p class="lead"><strong>@Html.DisplayNameFor(model => model.TaskContent)</strong></p>
                        <p class="lead">@Html.DisplayFor(model => model.TaskContent)</p>
                        <p class="lead"><strong>@Html.DisplayNameFor(model => model.LoggedHours)</strong></p>
                        <p class="lead">@Html.DisplayFor(model => model.LoggedHours)</p>
                        <p class="lead"><strong>@Html.DisplayNameFor(model => model.DateCreation)</strong></p>
                        <p class="lead">@Html.DisplayFor(model => model.DateCreation)</p>
                        <p class="lead"><strong>@Html.DisplayNameFor(model => model.DateLastEdit)</strong></p>
                        <p class="lead">@Html.DisplayFor(model => model.DateLastEdit)</p>
                        <p class="lead"><strong>Creator</strong></p>
                        <p class="lead">@Model.Users.Where(u => u.Id == Model.ParentUserId).FirstOrDefault().Username</p>
                        <p class="lead"><strong>Assigned User</strong></p>
                        <p class="lead">@Model.Users.Where(u => u.Id == Model.ParentUserId).FirstOrDefault().Username</p>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
        </div>
        @using (Html.BeginForm())
            {
            @Html.AntiForgeryToken()
            <div class="form-group">
                @Html.HiddenFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-4">
                    @Html.HiddenFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
    <!-- jQuery -->
    <script src="/vendor/jquery/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script src="/vendor/metisMenu/metisMenu.min.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="/dist/js/sb-admin-2.js"></script>
</body>
</html>

TaskManagerV2/TaskManagerV2/Views/TasksManagement/Details.cshtml
@model TaskManagerV2.ViewModels.Tasks.TaskDetailsVM

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
    <!-- Bootstrap Core CSS -->
    <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- MetisMenu CSS -->
    <link href="/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="/dist/css/sb-admin-2.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <div class="container">
        @Html.Partial("/Views/Shared/Menu.cshtml")
        <div class="row" style="margin-top: 10px">
            <div class="col-sm-offset-4 col-md-8">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Task
                    </div>
                    <div class="panel-body">
                        <p class="lead"><strong>@Html.DisplayNameFor(model => model.Item.Title)</strong></p>
                        <p class="lead">@Html.DisplayFor(model => model.Item.Title)</p>
                        <p class="lead"><strong>@Html.DisplayNameFor(model => model.Item.TaskContent)</strong></p>
                        <p class="lead">@Html.DisplayFor(model => model.Item.TaskContent)</p>
                        <p class="lead"><strong>@Html.DisplayNameFor(model => model.Item.LoggedHours)</strong></p>
                        <p class="lead">@Html.DisplayFor(model => model.Item.LoggedHours)</p>
                        <p class="lead"><strong>@Html.DisplayNameFor(model => model.Item.DateCreation)</strong></p>
                        <p class="lead">@Html.DisplayFor(model => model.Item.DateCreation)</p>
                        <p class="lead"><strong>@Html.DisplayNameFor(model => model.Item.DateLastEdit)</strong></p>
                        <p class="lead">@Html.DisplayFor(model => model.Item.DateLastEdit)</p>
                        <p class="lead"><strong>Creator</strong></p>
                        <p class="lead">@Model.Users.Where(u => u.Id == Model.Item.ParentUserId).FirstOrDefault().Username</p>
                        <p class="lead"><strong>Assigned User</strong></p>
                        <p class="lead">@Model.Users.Where(u => u.Id == Model.Item.ParentUserId).FirstOrDefault().Username</p>

                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
        </div>
        @{ Html.RenderPartial("/Views/Shared/GenericFilter.cshtml", Model.CommentsFilter); }
        <div class="row" style="margin-top:20px;">
            <div class="col-md-8 col-sm-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Comments |
                        @Html.ActionLink("Add Comment", "Edit", "CommentsManagement", new { parentTaskId = Model.Item.Id }, null)
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>
                                            Comment Content
                                        </th>
                                        <th>
                                            Assigned User
                                        </th>
                                        <th>

                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.Comments)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.CommentContent)
                                            </td>
                                            <td>
                                                @Model.Users.Where(u => u.Id == item.AssignedUserId).FirstOrDefault().Username
                                            </td>
                                            <td>
                                                @Html.ActionLink("Edit", "Edit", "CommentsManagement", new { id = item.Id, parentTaskId = item.ParentTaskId }, null) |
                                                @Html.ActionLink("Delete", "Delete", "CommentsManagement", new { id = item.Id }, null)

                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                        <!-- /.table-responsive -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
        </div>
        @{ Html.RenderPartial("/Views/Shared/GenericPager.cshtml", Model.CommentsPager);}

        @{ Html.RenderPartial("/Views/Shared/GenericFilter.cshtml", Model.LogworkFilter); }
        <div class="row" style="margin-top:20px;">
            <div class="col-md-8 col-sm-offset-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Comments |
                        @Html.ActionLink("Add Logwork", "Edit", "LogworksManagement", new { parentTaskId = Model.Item.Id }, null)
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>
                                            Logwork Hours
                                        </th>
                                        <th>

                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.Logworks)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.LoggedHours)
                                            </td>
                                            <td>
                                                @Html.ActionLink("Edit", "Edit", "LogworksManagement", new { id = item.Id, parentTaskId = item.ParentTaskId }, null) |
                                                @Html.ActionLink("Delete", "Delete", "LogworksManagement", new { id = item.Id }, null)

                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                        <!-- /.table-responsive -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
        </div>
        @{ Html.RenderPartial("/Views/Shared/GenericPager.cshtml", Model.LogworksPager);}

        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.Item.Id }) |
            @Html.ActionLink("Back to List", "Index")
        </p>
    </div>
    <!-- jQuery -->
    <script src="/vendor/jquery/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script src="/vendor/metisMenu/metisMenu.min.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="/dist/js/sb-admin-2.js"></script>
</body>
</html>

TaskManagerV2/TaskManagerV2/Views/TasksManagement/Edit.cshtml
@model TaskManagerV2.ViewModels.Tasks.SaveTaskVM

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <!-- Bootstrap Core CSS -->
    <link href="/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- MetisMenu CSS -->
    <link href="/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="/dist/css/sb-admin-2.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" type="text/css" media="screen" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href="./css/prettify-1.0.css" rel="stylesheet">
    <link href="./css/base.css" rel="stylesheet">
    <link href="//cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/build/css/bootstrap-datetimepicker.css" rel="stylesheet">
    <script async="" src="//www.google-analytics.com/analytics.js"></script>
    <script type="text/javascript" src="//code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>
    <script src="//cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/src/js/bootstrap-datetimepicker.js"></script>
</head>
<body>
    <div class="container">
        @Html.Partial("/Views/Shared/Menu.cshtml")
        <div class="row col-md-8 col-sm-offset-4">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Task</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.HiddenFor(model => model.ParentUserId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-4">
                            @Html.HiddenFor(model => model.ParentUserId, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ParentUserId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-4">
                            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TaskContent, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-4">
                            @Html.EditorFor(model => model.TaskContent, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TaskContent, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.LoggedHours, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-4">
                            @Html.EditorFor(model => model.LoggedHours, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.LoggedHours, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.AssignedUserId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-4">
                            <select class="form-control" name="AssignedUserId">
                                @foreach (var item in Model.Users)
                                {
                                    <option value="@item.Id">@item.Username</option>
                                }
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.DateCreation, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class='input-group date' id='datetimepickerCreate'>
                                    @{
                                        DateTime datetime = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 01, 12, 0, 0);

                                    }
                                    <input type='text' name="DateCreation"
                                           value="@if (Model.Id > 0) { @Model.DateCreation } @if (Model.Id <= 0) { @datetime} "
                                           class="form-control" />
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>
                            </div>
                            <script type="text/javascript">
                                $('#datetimepickerCreate').datetimepicker();
                            </script>
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.DateLastEdit, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-4">
                            <div class="form-group">
                                <div class="input-group date" id='datetimepickerEdit'>
                                    <input type="text" name="DateLastEdit"
                                           value="@if (Model.Id > 0) { @Model.DateLastEdit } @if (Model.Id <= 0) { @datetime } "
                                           class="form-control" />
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>
                            </div>
                            <script type="text/javascript">
                                $('#datetimepickerEdit').datetimepicker();
                            </script>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </div>
                </div>
                                        }
        </div>
    </div>
    <!-- jQuery -->
    <script src="/vendor/jquery/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script src="/vendor/metisMenu/metisMenu.min.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="/dist/js/sb-admin-2.js"></script>
</body>
</html>