TaskManagerV2/TaskManagerV2/ViewModels/Shared/BaseListVM.cs
using Common.Entities;
using DatabaseAccess.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TaskManagerV2.Annotations;

namespace TaskManagerV2.ViewModels.Shared
{
    public class BaseListVM

    {
        [SkipFilter]
        public List<User> Users { get; set; }
        [SkipFilter]
        public List<Task> Tasks { get; set; }
        [SkipFilter]
        public List<Comment> Comments { get; set; }
        [SkipFilter]
        public List<Logwork> Logworks { get; set; }
        public BaseListVM()
        {
            Users = new UsersRepository().GetAll();
            Tasks = new TasksRepository().GetAll();
            Comments = new CommentsRepository().GetAll();
            Logworks = new LogworksRepository().GetAll();
        }
    }
}

TaskManagerV2/TaskManagerV2/ViewModels/Shared/FilterVM.cs
using Common.Entities;
using DatabaseAccess.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TaskManagerV2.Annotations;

namespace TaskManagerV2.ViewModels.Shared
{
    public class FilterVM : BaseListVM
    {
        [SkipFilter]
        public string Prefix { get; set; }
    }
}

TaskManagerV2/TaskManagerV2/ViewModels/Shared/GenericFilterVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using TaskManagerV2.Annotations;

namespace TaskManagerV2.ViewModels.Shared
{
    public abstract class GenericFilterVM<T> : FilterVM
    {
        public abstract Expression<Func<T, bool>> BuildFilter();
    }
}

TaskManagerV2/TaskManagerV2/ViewModels/Shared/PagerVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TaskManagerV2.ViewModels.Shared
{
    public class PagerVM
    {
        public string Prefix { get; set; }
        public int CurrentPage { get; set; }
        public int ItemsPerPage { get; set; }
        public int PageCount { get; set; }
    }
}

TaskManagerV2/TaskManagerV2/Controllers/TasksManagementController.cs
using Common.Entities;
using DatabaseAccess.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskManagerV2.Models;
using TaskManagerV2.ViewModels.Comments;
using TaskManagerV2.ViewModels.Logworks;
using TaskManagerV2.ViewModels.Shared;
using TaskManagerV2.ViewModels.Tasks;

namespace TaskManagerV2.Controllers
{
    public class TasksManagementController : BaseController<Task, TasksRepository, SaveTaskVM, IndexTaskVM, TasksFilterVM>
    {
        public override void AddItemToIndexVM(IndexTaskVM model)
        {
            UsersRepository usersRepo = new UsersRepository();
            model.Users = usersRepo.GetAll();
        }
        public override void AddItemToSaveVM(SaveTaskVM model)
        {
            UsersRepository usersRepo = new UsersRepository();
            model.Users = usersRepo.GetAll();
        }
        public override void PopulateItem(SaveTaskVM model, Task item)
        {
            model.ParentUserId = AuthenticationManager.LoggedUser.Id;
            model.Title = item.Title;
            model.TaskContent = item.TaskContent;
            model.LoggedHours = item.LoggedHours;
            model.AssignedUserId = item.AssignedUserId;
            model.DateCreation = item.DateCreation;
            model.DateLastEdit = item.DateLastEdit;
        }

        public override void PopulateViewModel(Task item, SaveTaskVM model)
        {
            item.ParentUserId = AuthenticationManager.LoggedUser.Id;
            item.Title = model.Title;
            item.TaskContent = model.TaskContent;
            item.LoggedHours = model.LoggedHours;
            item.AssignedUserId = model.AssignedUserId;
            item.DateCreation = model.DateCreation;
            item.DateLastEdit = model.DateLastEdit;
        }
        [HttpGet]
        public ActionResult Details(TaskDetailsVM model)
        {
            
            TasksRepository tasksRepository = new TasksRepository();
            model.Item = tasksRepository.GetById(model.Id);
            if (model == null)
                return RedirectToAction("Index", "Tasks");

            UsersRepository usersRepository = new UsersRepository();
            model.Users = usersRepository.GetAll();
            CommentsRepository commentsRepo = new CommentsRepository();
            LogworksRepository logworkRepo = new LogworksRepository();
            model.CommentsPager = model.CommentsPager ?? new PagerVM();
            model.CommentsFilter = model.CommentsFilter ?? new CommentsFilterVM();
            model.CommentsFilter.Id = model.Id;
            var filter = model.CommentsFilter.BuildFilter();
            model.CommentsPager.Prefix = "CommentsPager";
            model.CommentsFilter.Prefix = "CommentsFilter";
            model.CommentsPager.ItemsPerPage = model.CommentsPager.ItemsPerPage == 0 ? 5 : model.CommentsPager.ItemsPerPage;
            model.CommentsPager.PageCount = (int)Math.Ceiling(commentsRepo.Count(filter) / (decimal)model.CommentsPager.ItemsPerPage);
            model.CommentsPager.PageCount = model.CommentsPager.PageCount == 0 ? 1 : model.CommentsPager.PageCount;
            model.Comments = commentsRepo.GetAll(filter, model.CommentsPager.CurrentPage, model.CommentsPager.ItemsPerPage);

            model.LogworksPager = model.LogworksPager ?? new PagerVM();
            model.LogworkFilter = model.LogworkFilter ?? new LogworkFilterVM();
            model.LogworkFilter.Id = model.Id;
            var logworkFilter = model.LogworkFilter.BuildFilter();
            model.LogworksPager.Prefix = "LogworksPager";
            model.LogworkFilter.Prefix = "LogworkFilter";
            model.LogworksPager.ItemsPerPage = model.LogworksPager.ItemsPerPage == 0 ? 5 : model.LogworksPager.ItemsPerPage;
            model.LogworksPager.PageCount = (int)Math.Ceiling(logworkRepo.Count(logworkFilter) / (decimal)model.LogworksPager.ItemsPerPage);
            model.LogworksPager.PageCount = model.LogworksPager.PageCount == 0 ? 1 : model.LogworksPager.PageCount;
            model.Logworks = logworkRepo.GetAll(logworkFilter, model.LogworksPager.CurrentPage, model.LogworksPager.ItemsPerPage);

            return View(model);
        }
    }
}

TaskManagerV2/TaskManagerV2/Controllers/UsersManagementController.cs
using Common.Entities;
using DatabaseAccess.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskManagerV2.ViewModels.Shared;
using TaskManagerV2.ViewModels.Users;
using TaskManagerV2.Annotations;

namespace TaskManagerV2.Controllers
{
    [AdministrationAnnotation]
    public class UsersManagementController : BaseController<User, UsersRepository, SaveUserVM, IndexUserVM, UsersFilterVM>
    {
        public override void PopulateItem(SaveUserVM model, User item)
        {
            model.Username = item.Username;
            model.Password = item.Password;
            model.FirstName = item.FirstName;
            model.LastName = item.LastName;
            model.IsAdmin = item.IsAdmin;
        }

        public override void PopulateViewModel(User item, SaveUserVM model)
        {
            item.Username = model.Username;
            item.Password = model.Password;
            item.FirstName = model.FirstName;
            item.LastName = model.LastName;
            item.IsAdmin = model.IsAdmin;
        }
    }
}

TaskManagerV2/TaskManagerV2/Views/Shared/GenericFilter.cshtml
@model TaskManagerV2.ViewModels.Shared.FilterVM

@{

    string controllerName = this.ViewContext.RouteData.Values["controller"].ToString();
    string actionName = this.ViewContext.RouteData.Values["action"].ToString();
    var piPrefix = Model.GetType().GetProperty("Prefix");
    string prefix = piPrefix.GetValue(Model).ToString();
    var properties = new List<System.Reflection.PropertyInfo>(Model.GetType().GetProperties());
    string filterLinkTemplate = "/" + controllerName + "/" + actionName + "?";
}

<div class="row" style="margin-top:20px;">
    <div class="col-md-8 col-sm-offset-4">
        <form action="@filterLinkTemplate" method="get">
            @foreach (var key in this.Request.QueryString.AllKeys)
            {
                if (properties.Find(x => prefix + "." + x.Name == key) != null)
                {
                    continue;
                }

                <input type="hidden" name="@key" value="@Request.QueryString[key]" />
            }

            @foreach (var val in this.ViewContext.RouteData.Values)
            {
                if (val.Key == "controller" || val.Key == "action" || properties.Find(x => prefix + "." + x.Name == val.Key) != null)
                {
                    continue;
                }

                <input type="hidden" name="@val.Key" value="@val.Value.ToString()" />
            }

            @foreach (var test in properties)
            {
                if (test.CustomAttributes.FirstOrDefault(a => a.AttributeType.IsAssignableFrom(typeof(TaskManagerV2.Annotations.SkipFilter))) != null)
                {
                    continue;

                }
                if (test.CustomAttributes.FirstOrDefault(a => a.AttributeType.IsAssignableFrom(typeof(TaskManagerV2.Annotations.UsersDropdown))) != null)
                {

                    <div class="col-md-3" style="margin-top: 15px;">
                        <select class="form-control" name="@(prefix).@(test.Name)">
                            <option value="0">All Items</option>
                            @foreach (var item in Model.Users)
                            {
                                <option value="@item.Id">@item.Username</option>
                            }
                        </select>
                    </div>
                    continue;
                }

                var value = test.GetValue(Model, null);
                <div class="col-md-3">
                    <span>@test.Name</span>
                    <input type="search" class="form-control input-sm" name="@(prefix).@(test.Name)" value="@(value == null ? "" : value.ToString())" aria-controls="dataTables-example" />
                </div>
            }
            <button style="margin-top:16px;" class="btn btn-default" type="submit" value="Filter">Search <i class="fa fa-search"></i></button>
        </form>
    </div>
</div>

TaskManagerV2/TaskManagerV2/Views/Shared/GenericPager.cshtml
@model TaskManagerV2.ViewModels.Shared.PagerVM

@{
    string controllerName = this.ViewContext.RouteData.Values["controller"].ToString();
    string actionName = this.ViewContext.RouteData.Values["action"].ToString();
    string itemsPerPageLinkTemplate = "http://localhost:59967/" + controllerName + "/" + actionName + "?";
    string pagerLinkTemplate = "/" + controllerName + "/" + actionName + "?";
}
@{
    foreach (var key in this.Request.QueryString.AllKeys)
    {
        if (key == (Model.Prefix + ".ItemsPerPage") || key == (Model.Prefix + ".CurrentPage"))
        {
            continue;
        }
        itemsPerPageLinkTemplate += key + "=" + this.Request.QueryString[key] + "&";
        pagerLinkTemplate += key + "=" + this.Request.QueryString[key] + "&";
    }

    foreach (var val in this.ViewContext.RouteData.Values)
    {
        if (val.Key == "controller" || val.Key == "action")
        {
            continue;
        }
        itemsPerPageLinkTemplate += val.Key + "=" + val.Value + "&";
        pagerLinkTemplate += val.Key + "=" + val.Value + "&";
    }
}
<script>
    function @(Model.Prefix)_ItemsPerPage_Change() {

        var value = $("#@(Model.Prefix)_ItemsPerPage").val();
        var link = '@Html.Raw(itemsPerPageLinkTemplate)@(Model.Prefix).ItemsPerPage=' + value;

        window.location = link;
    }
</script>

<div class="row">
    <div class="col-sm-2 col-sm-offset-4">
        <div class="dataTables_length" id="dataTables-example_length">
            <label>
                Show
                <select id="@(Model.Prefix)_ItemsPerPage" name="@(Model.Prefix).ItemsPerPage" onchange="@(Model.Prefix)_ItemsPerPage_Change();" aria-controls="dataTables-example" class="form-control input-sm">
                    <option @(Model.ItemsPerPage == 1 ? "selected" : "") value="1">1</option>
                    <option @(Model.ItemsPerPage == 5 ? "selected" : "") value="5">5</option>
                    <option @(Model.ItemsPerPage == 10 ? "selected" : "") value="10">10</option>
                </select> entries
            </label>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="dataTables_paginate paging_simple_numbers" id="dataTables-example_paginate">
            <ul class="pagination">
                @for (int i = 0; i < Model.PageCount; i++)
                {
                    <li class="@(i == Model.CurrentPage ? "paginate_button active" : "paginate_button")" aria- aria-controls="dataTables-example" tabindex="0">
                        <a href="@pagerLinkTemplate@(Model.Prefix).CurrentPage=@i&@(Model.Prefix).ItemsPerPage=@Model.ItemsPerPage">@(i + 1)</a>
                    </li>
                }
            </ul>
        </div>
    </div>
</div>

TaskManagerV2/TaskManagerV2/Views/Shared/Menu.cshtml
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>

        @Html.ActionLink("Task Manager", "Index", "Home", null, new { @class = "navbar-brand" })

    </div>
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-right">
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                @if (TaskManagerV2.Models.AuthenticationManager.LoggedUser != null)
                {
                    <li>
                        <a href="#"><i class="fa fa-user fa-fw"></i>@TaskManagerV2.Models.AuthenticationManager.LoggedUser.Username</a>
                    </li>
                            <li class="divider"></li>
                }

                <li>
                    @if (TaskManagerV2.Models.AuthenticationManager.LoggedUser == null)
                    {
                        <a href="@Url.Action("LogIn", "Home")">
                            <i class="fa fa-sign-out fa-fw"></i>Login
                        </a>

                    <div class="divider"></div>

                        <a href="@Url.Action("Register", "Home")">
                            <i class="fa fa-bomb"></i>Join in
                        </a>
                    }
                    @if (TaskManagerV2.Models.AuthenticationManager.LoggedUser != null)
                    {
                        <a href="@Url.Action("LogOut", "Home")">
                            <i class="fa fa-sign-out fa-fw"></i>Logout
                        </a>
                    }

                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->
    @if (TaskManagerV2.Models.AuthenticationManager.LoggedUser != null)
            {
        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav in" id="side-menu">
                    @if (TaskManagerV2.Models.AuthenticationManager.LoggedUser.IsAdmin == true)
                    {
                        <li>
                            <a href="@Url.Action("Index", "UsersManagement")"><i class="fa fa-user fa-fw"></i>Users</a>
                        </li>
                    }
                    <li>
                        <a href="@Url.Action("Index", "TasksManagement")"><i class="fa fa-pencil-square-o fa-fw"></i>Tasks</a>
                    </li>
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
    }
    <!-- /.navbar-static-side -->
</nav>